export const games = [
  {
    id: 1,
    image: "https://cdn.axieinfinity.com/marketplace-website/banner/game/origins-game.png",
    banner: "https://cdn.axieinfinity.com/marketplace-website/banner/game/origins-banner-key-art.png",
    name: "Axie Infinity: Origins",
    genre: ["Turn-based", "Strategy", "Adventure"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Sky Mavis",
    socials: {
      website: "https://axieinfinity.com/",
      twitter: "https://twitter.com/AxieInfinity",
      youtube: "https://www.youtube.com/channel/UCbFwe3COkDrbNsbMyGNCsDg",
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "Axie Infinity Origins is a card-based strategy game where players collect, own, and use an infinite variety of creatures called Axies to battle. Players can take down evil Chimeras in the Adventure mode or challenge other players in the Arena to reach the top of the Leaderboard.",
  },
  {
    id: 2,
    image: "https://cdn.skymavis.com/mavis-hub/assets/1721977430-icon.png",
    banner: "https://cdn.skymavis.com/mavis-hub/assets/1721977471-sc_2.jpg",
    name: "Axie Classic",
    genre: ["Turn-based", "Strategy"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Sky Mavis",
    socials: {
      website: "https://axieinfinity.com/",
      twitter: "https://twitter.com/AxieInfinity",
      youtube: "https://www.youtube.com/channel/UCbFwe3COkDrbNsbMyGNCsDg",
    },
    platforms: ["Windows", "Android", "macOS"],
    description:
      "Classic, released in December 2019, grew the Axie community from a ragtag band of a few hundred missionaries to millions. The game is structured as a turn-based card battler where players create teams of Axies to duke it out in the arena. Axies draw cards based on the body parts they posses and you must play these cards at the optimal time and order to maximize your chance of victory. Classic was the first game ever to distribute in-game resources as ERC20 tokens.",
  },
  {
    id: 3,
    image: "/games/elumia_image.jpg",
    banner: "/games/elumia_banner.jpg",
    name: "Legends of Elumia",
    genre: ["MMORPG"],
    isPlayable: false,
    isVerified: false,
    playableTime: "",
    creator: "",
    socials: {
      website: "https://www.elumia.io/",
      twitter: "https://x.com/PlayElumia",
    },
    platforms: ["Windows", "macOS"],
    description:
      "Legends of Elumia is a next-generation, massively multiplayer online role-playing game(MMORPG), leading the way for players to gain full ownership of their in-game assets using revolutionary new mechanics.",
  },
  {
    id: 4,
    image: "/games/red_covenant_image.jpg",
    banner: "/games/red_covenant_banner.webp",
    name: "Red Covenant",
    genre: ["free-to-play", "JRPG", "Strategy"],
    isPlayable: true,
    isVerified: false,
    playableTime: "",
    creator: "Avarik Saga",
    socials: {
      website: "https://avariksaga.com/",
      twitter: "https://x.com/avariksaga",
      discord: "https://discord.com/invite/9zXFDCp9mc",
      youtube: "https://www.youtube.com/channel/UCc8Rc_5LTEZO2fcem1WEOyw"
    },
    platforms: ["Android"],
    description:
      "Immerse yourself in the captivating world of 'Red Covenant' a dark and enchanting game set in a fantasy realm teeming with mystery and peril. Uncover the secrets of forsaken maidens, ethereal beings bound by blood contracts, as you embark on a thrilling journey through a land shrouded in darkness.",
  },
  {
    id: 5,
    image: "/games/aof_image.jpg",
    banner: "https://aofweb.s3.ap-east-1.amazonaws.com/front/ahome/AOF/4.png",
    name: "Arena of Faith",
    genre: ["MOBA"],
    isPlayable: true,
    isVerified: false,
    playableTime: "",
    creator: "",
    socials: {
      website: "https://aof.global/",
      twitter: "https://x.com/moba_aof",
      discord: "https://discord.com/invite/moba-aof",
      youtube: "https://www.youtube.com/@moba_aof"
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "Web3 revolution start from MOBA. Empowering seamless global and cross-Platform connectivity, next-gen rendering, and secure decentralized settlements with POFS technology.",
  },
  {
    id: 6,
    image: "/games/fishing_frenzy_image.jpg",
    banner: "/games/fishing_frenzy_banner.jpg",
    name: "Fishing Frenzy",
    genre: [],
    isPlayable: false,
    isVerified: false,
    playableTime: "",
    creator: "Uncharted",
    socials: {
      website: "https://fishingfrenzy.co/",
      twitter: "https://x.com/FishingFrenzyCo",
      discord: "https://discord.com/invite/unchartedgg",
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "Fishing Frenzy is a cozy mobile fishing RPG that blends relaxing gameplay with a player-driven economy. Cast your line, reel in a variety of fish, and work your way up the competitive leaderboards!.",
  },
  {
    id: 7,
    image: "/games/nifty_image.jpg",
    banner: "/games/nifty_banner.jpg",
    name: "Nifty Island",
    genre: [],
    isPlayable: false,
    isVerified: false,
    playableTime: "",
    creator: "",
    platforms: ["Windows", "iOS", "Android", "macOS"],
    socials: {
      website: "https://www.niftyisland.com/",
      twitter: "https://x.com/Nifty_Island",
      discord: "https://discord.com/invite/4WT9BbEK82",
    },
    description:
      "Nifty Island is a community-driven gaming platform where players can build and play games together, explore player-created islands, and compete for compelling rewards. Build your own island. Invite your friends. Win rewards. Play any game that you can imagine and engage in prize-fueled competitions. The internet's best communities play on Nifty Island.",
  },
  {
    id: 8,
    image: "/games/pirate_nation_image.png",
    banner: "/games/pirate_nation_banner.webp",
    name: "Pirate Nation",
    genre: ["RPG", "Adventure"],
    isPlayable: true,
    isVerified: false,
    playableTime: "",
    creator: "",
    socials: {
      website: "https://piratenation.game/",
      twitter: "https://x.com/PirateNation",
      discord: "https://discord.com/invite/piratenation",
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "A fully onchain RPG, filled with high seas adventure, treasure, & unexpected surprises.",
  },
  {
    id: 9,
    image: "/games/sunflower_image.png",
    banner: "/games/sunflower_banner.png",
    name: "Sunflower Land",
    genre: ["Farm", "Pixel Art"],
    isPlayable: true,
    isVerified: false,
    playableTime: "",
    creator: "",
    socials: {
      website: "https://sunflower-land.com/",
      twitter: "https://x.com/0xSunflowerLand",
      discord: "https://discord.com/invite/sunflowerland",
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "Online farming game. Farm, Gather, Cook, Raise Animals, Fish, Craft & Trade.",
  },
];
