export const games = [
  {
    id: "axie-infinity-origin",
    image: "https://cdn.axieinfinity.com/marketplace-website/banner/game/origins-game.png",
    banner: "https://cdn.axieinfinity.com/marketplace-website/banner/game/origins-banner-key-art.png",
    name: "Axie Infinity: Origins",
    genre: ["Turn-based", "Strategy", "Adventure"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Sky Mavis",
    socials: {
      website: "https://axieinfinity.com/",
      twitter: "https://twitter.com/AxieInfinity",
      youtube: "https://www.youtube.com/watch?v=X2z_YIeettE",
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "Axie Infinity Origins is a card-based strategy game where players collect, own, and use an infinite variety of creatures called Axies to battle. Players can take down evil Chimeras in the Adventure mode or challenge other players in the Arena to reach the top of the Leaderboard.",
  },
  {
    id: "axie-infinity-classic",
    image: "https://cdn.skymavis.com/mavis-hub/assets/1721977430-icon.png",
    banner: "https://cdn.skymavis.com/mavis-hub/assets/1721977471-sc_2.jpg",
    name: "Axie Classic",
    genre: ["Turn-based", "Strategy"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Sky Mavis",
    socials: {
      website: "https://axieinfinity.com/",
      twitter: "https://twitter.com/AxieInfinity",
      youtube: "https://www.youtube.com/watch?v=H0Dh_uvCuFU",
    },
    platforms: ["Windows", "Android", "macOS"],
    description:
      "Classic, released in December 2019, grew the Axie community from a ragtag band of a few hundred missionaries to millions. The game is structured as a turn-based card battler where players create teams of Axies to duke it out in the arena. Axies draw cards based on the body parts they posses and you must play these cards at the optimal time and order to maximize your chance of victory. Classic was the first game ever to distribute in-game resources as ERC20 tokens.",
  },
  {
    id: "League-of-Elumia",
    image: "/games/elumia_image.jpg",
    banner: "/games/elumia_banner.jpg",
    name: "Legends of Elumia",
    genre: ["MMORPG"],
    isPlayable: true,
    isVerified: false,
    playableTime: "",
    creator: "",
    socials: {
      website: "https://www.elumia.io/",
      twitter: "https://x.com/PlayElumia",
    },
    platforms: ["Windows", "macOS"],
    description:
      "Legends of Elumia is a next-generation, massively multiplayer online role-playing game(MMORPG), leading the way for players to gain full ownership of their in-game assets using revolutionary new mechanics.",
  },
  {
    id: "Red-Covenant",
    image: "/games/red_covenant_image.jpg",
    banner: "/games/red_covenant_banner.webp",
    name: "Red Covenant",
    genre: ["free-to-play", "JRPG", "Strategy"],
    isPlayable: true,
    isVerified: false,
    playableTime: "",
    creator: "Avarik Saga",
    socials: {
      website: "https://avariksaga.com/",
      twitter: "https://x.com/avariksaga",
      discord: "https://discord.com/invite/9zXFDCp9mc",
      youtube: "https://www.youtube.com/channel/UCc8Rc_5LTEZO2fcem1WEOyw"
    },
    platforms: ["Android"],
    description:
      "Immerse yourself in the captivating world of 'Red Covenant' a dark and enchanting game set in a fantasy realm teeming with mystery and peril. Uncover the secrets of forsaken maidens, ethereal beings bound by blood contracts, as you embark on a thrilling journey through a land shrouded in darkness.",
  },
  {
    id: "Arena-of-Faith",
    image: "/games/aof_image.jpg",
    banner: "https://aofweb.s3.ap-east-1.amazonaws.com/front/ahome/AOF/4.png",
    name: "Arena of Faith",
    genre: ["MOBA"],
    isPlayable: true,
    isVerified: false,
    playableTime: "",
    creator: "",
    socials: {
      website: "https://aof.global/",
      twitter: "https://x.com/moba_aof",
      discord: "https://discord.com/invite/moba-aof",
      youtube: "https://www.youtube.com/@moba_aof"
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "Web3 revolution start from MOBA. Empowering seamless global and cross-Platform connectivity, next-gen rendering, and secure decentralized settlements with POFS technology.",
  },
  {
    id: "Fishing-Frenzy",
    image: "/games/fishing_frenzy_image.jpg",
    banner: "/games/fishing_frenzy_banner.jpg",
    name: "Fishing Frenzy",
    genre: [],
    isPlayable: false,
    isVerified: false,
    playableTime: "",
    creator: "Uncharted",
    socials: {
      website: "https://fishingfrenzy.co/",
      twitter: "https://x.com/FishingFrenzyCo",
      discord: "https://discord.com/invite/unchartedgg",
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "Fishing Frenzy is a cozy mobile fishing RPG that blends relaxing gameplay with a player-driven economy. Cast your line, reel in a variety of fish, and work your way up the competitive leaderboards!.",
  },
  {
    id: "Nifty-Island",
    image: "/games/nifty_image.jpg",
    banner: "/games/nifty_banner.jpg",
    name: "Nifty Island",
    genre: [],
    isPlayable: true,
    isVerified: false,
    playableTime: "",
    creator: "",
    platforms: ["Windows", "iOS", "Android", "macOS"],
    socials: {
      website: "https://www.niftyisland.com/",
      twitter: "https://x.com/Nifty_Island",
      discord: "https://discord.com/invite/4WT9BbEK82",
    },
    description:
      "Nifty Island is a community-driven gaming platform where players can build and play games together, explore player-created islands, and compete for compelling rewards. Build your own island. Invite your friends. Win rewards. Play any game that you can imagine and engage in prize-fueled competitions. The internet's best communities play on Nifty Island.",
  },
  {
    id: "Pirate-Nation",
    image: "/games/pirate_nation_image.png",
    banner: "/games/pirate_nation_banner.webp",
    name: "Pirate Nation",
    genre: ["RPG", "Adventure"],
    isPlayable: true,
    isVerified: false,
    playableTime: "",
    creator: "",
    socials: {
      website: "https://piratenation.game/",
      twitter: "https://x.com/PirateNation",
      discord: "https://discord.com/invite/piratenation",
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "A fully onchain RPG, filled with high seas adventure, treasure, & unexpected surprises.",
  },
  {
    id: "Sunflower-Land",
    image: "/games/sunflower_image.png",
    banner: "/games/sunflower_banner.png",
    name: "Sunflower Land",
    genre: ["Farm", "Pixel Art"],
    isPlayable: true,
    isVerified: false,
    playableTime: "",
    creator: "",
    socials: {
      website: "https://sunflower-land.com/",
      twitter: "https://x.com/0xSunflowerLand",
      discord: "https://discord.com/invite/sunflowerland",
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "Online farming game. Farm, Gather, Cook, Raise Animals, Fish, Craft & Trade.",
  },
  {
    id: "Axie-Infinity-Homeland",
    image: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1706002040-homeland_app_icon.png",
    banner: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1706004536-screenshot_1.jpg",
    name: "Axie Infinity: Homeland",
    genre: ["Strategy", "Adventure", "Build & Battle"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Sky Mavis",
    socials: {
      website: "https://axieinfinity.com/",
      twitter: "https://twitter.com/AxieInfinity",
      youtube: "https://www.youtube.com/watch?v=ZeySoIxFCJQ",
    },
    platforms: ["Windows", "Android", "macOS"],
    description:
      "Start your own village on the breathtaking planet of Lunacia. Lead your axies as they harvest, craft, and build towards a stronger homeland. Embrace infinity!",
  },
  {
    id: "Pixel",
    image: "https://cdn.skymavis.com/mavis-hub/assets/1733298752-pixels-logo.png",
    banner: "https://cdn.skymavis.com/mavis-hub/assets/1733300981-pixels.jpg",
    name: "Pixel",
    genre: ["Strategy", "Adventure", "Build & Battle"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Banger Inc",
    socials: {
      website: "https://www.pixels.xyz/",
      twitter: "https://x.com/pixels_online",
      youtube: "https://www.youtube.com/watch?v=i6dt095woS8",
    },
    platforms: ["Windows", "Android", "macOS"],
    description:
      "Pixels is a vast, pixel-art-inspired MMORPG where your farming journey is just the beginning of an exciting adventure. In this expansive world, every pixel tells a story, and every choice you make shapes your destiny. Explore a living, breathing universe where you can cultivate your land, interact with a dynamic ecosystem, and engage in a community-driven experience like no other.",
  },
  {
    id: "Wonder-Wars",
    image: "/games/wonderwars_image.jpg",
    banner: "/games/wonderwars_banner.jpg",
    name: "Wonder Wars",
    genre: ["free-to-play", "PvE", "PvP"],
    isPlayable: true,
    isVerified: false,
    playableTime: "",
    creator: "Hello Monster",
    socials: {
      website: "https://wonderwars.game/",
      twitter: "https://x.com/WonderWarsGame",
      discord: "https://discord.com/invite/nD2ZYDCXGV",
    },
    platforms: ["Android", "iOS"],
    description:
      "Wonder Wars is a free-to-play mobile strategy game developed by indie studio Hello Monster. Build decks by selecting a hero and six troops, engage in lane-based 3D battles, and play PvE or PvP game modes.",
  },
  {
    id: "Rumble-Kong-League",
    image: "/games/rumblekong_image.jpg",
    banner: "/games/rumblekong_banner.png",
    name: "Rumble Kong League",
    genre: ["Basketball", "PvP"],
    isPlayable: true,
    isVerified: false,
    playableTime: "",
    creator: "",
    socials: {
      website: "https://www.rumblekongleague.com/",
      twitter: "https://x.com/RumbleKongs",
      discord: "https://discord.com/invite/rumblekongleague",
    },
    platforms: ["Android", "iOS"],
    description:
      "Rumble Kong League is a fast-paced 3v3 basketball game that blends sports action with Web3 innovation. Build teams of unique Kong NFTs and compete in casual matches or climb competitive leaderboards for rewards.",
  },
  {
    id: "De:Lithe-Last-Memories",
    image: "/games/lastmemories_image.png",
    banner: "/games/lastmemories_banner.jpg",
    name: "De:Lithe Last Memories",
    genre: ["Rogue-like", "RPG"],
    isPlayable: false,
    isVerified: false,
    playableTime: "",
    creator: "enish",
    socials: {
      website: "https://lastmemories.io/en/",
      twitter: "https://x.com/lastmemoriesen",
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "De:Lithe Last Memories is a roguelike MMORPG with fast-paced combat and strategic dungeon exploration where every battle is a test of skill and survival. Build, upgrade, and optimize their squads to face ever-evolving challenges in solo and multiplayer modes.",
  },
  {
    id: "Sekai-Glory",
    image: "/games/sekai_glory_image.jpg",
    banner: "/games/sekai_glory_banner.jpg",
    name: "Sekai Glory",
    genre: ["Trading Cards", "Gacha"],
    isPlayable: false,
    isVerified: false,
    playableTime: "",
    creator: "RNG Inc.",
    socials: {
      website: "https://www.sekaiglory.com/en",
      twitter: "https://x.com/SekaiGlory",
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "Web3 anime trading card game (TCG) with a variety of game modes — including an auto-battler. Collect, strategize, and compete to ascend leaderboards and earn in-game rewards. Own cards and artifacts, and dive into each character’s unique abilities and lore.",
  },
  {
    id: "WILD-FOREST",
    image: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1710172953-wf_logo.png",
    banner: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1710172983-artgallery_1.jpg",
    name: "WILD FOREST",
    genre: ["Strategy"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Zillion Whales",
    socials: {
      website: "https://playwildforest.io/",
      twitter: "https://twitter.com/playwildforest",
      youtube: "https://www.youtube.com/watch?v=jIXNoshQa3o"
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "Wild Forest is a single-screen real-time strategy game where players face off in fast, action-packed PvP battles. Compete by capturing areas, building armies, and outsmarting opponents to win by destroying their main base. ",
  },
  {
    id: "Ragnarok-Monster-World",
    image: "https://cdn.skymavis.com/mavis-hub/assets/1733296882-storelogo256x256.jpg",
    banner: "https://cdn.skymavis.com/mavis-hub/assets/rag-monster-world/game-asset-db3a1cab-e448-4405-a3b3-6cb51a63b3db.jpg",
    name: "Ragnarok Monster World",
    genre: ["Strategy"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "ZERO X AND",
    socials: {
      website: "https://ragmon.gg/",
      twitter: "https://x.com/ragmonNFT",
      youtube: "https://www.youtube.com/watch?v=jyCfdJGhIhw"
    },
    platforms: ["iOS", "Android",],
    description:
      "Ragnarok: Monster World is a Tower Defense & Monster Collecting game that officially uses the 'Ragnarok Online' IP. As the first to create official FT/NFTs with this iconic IP, it marks a groundbreaking venture. Begin your journey now!",
  },
  {
    id: "Pixel-Heroes-Adventure",
    image: "https://cdn.skymavis.com/mavis-hub/assets/1735180905-logoformavis.png",
    banner: "https://cdn.skymavis.com/mavis-hub/assets/1735295890-overviewformavis.png",
    name: "Pixel Heroes Adventure",
    genre: ["RPG", "MMORPG"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Z5 Games",
    socials: {
      website: "https://dapp.pixelheroes.io/",
      twitter: "https://x.com/PixelHeroesMMO",
      youtube: "https://www.youtube.com/watch?v=x915mSaB-DU"
    },
    platforms: ["iOS", "Android",],
    description:
      "Pixel Heroes Adventure is a world where humans and toys live together with various magical properties The peaceful toys of Pixel Heroes Adventure became corrupted by evil magic and started attacking humans. In response, humans studied magic to gain the power to resist the evil monsters and those who wielded this mysterious power were called HeroZ. Some toys gained power without being corrupted by evil magic and they were called ToyZ. Embark on an epic adventure to save the world of HeroZ and ToyZ",
  },
  {
    id: "Axie-infinity-Raylights",
    image: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1688981158-raylights-youtube-thumbnail.jpg",
    banner: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1689060594-sm_ch2_screenshot_a.jpg",
    name: "Axie infinity Raylights",
    genre: ["Land Cultivation", "Discovery", "Puzzle"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Quicksave",
    socials: {
      website: "https://hub.skymavis.com/games/raylights?from=%2Fgames&name=Browse+Games&filter=partnershipType%253Dsky-mavis",
      twitter: "https://x.com/QuicksaveLtd",
      youtube: "https://youtu.be/cGHkkIEu-20"
    },
    platforms: ["Windows", "macOS",],
    description:
      "Step into the enchanting world of Axie Infinity: Raylights, where a new and upgraded experience awaits not just landowners but EVERYONE! Join forces with fellow Axie-owners to sow minerals, uncover new combinations, utilize the maximum potential of Axie’s mineral familiarity, cultivate breathtaking plants, and create the most stunning land plots in Lunacia. With every step forward, unlock new minerals, secret recipes, and also captivating seasonal plants and minerals to enhance your land. Immerse yourself in the Raylights experience today, straight from your browser. No download or installation necessary. Let the adventure begin!",
  },
  {
    id: "Project-T-prototype",
    image: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1692030941-logo-t.jpg",
    banner: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1692030921-1.jpg",
    name: "Project T prototype",
    genre: ["Adventure", "RPG"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Sky mavis",
    socials: {
      website: "https://hub.skymavis.com/games/project-t?from=%2Fgames&name=Browse+Games&filter=partnershipType%253Dsky-mavis",
      twitter: "https://twitter.com/AxieInfinity",
      youtube: "https://youtu.be/HZrhGZXEnho"
    },
    platforms: ["Windows", "macOS",],
    description:
      "Project T is an early prototype of a new Axie game developed by Sky Mavis where players can interact with their Axies and fellow Axie owners – like a digital meetup! Play a variety of mini-games and access unique experiences as we build them out over time. In the future, we plan to integrate AXP with Project T as we reinforce the connective tissue between infinite Axie experiences.",
  },
  {
    id: "Apeiron",
    image: "https://cdn.skymavis.com/mavis-hub/assets/1733306114-104_logo_256x256.png",
    banner: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1709178757-01-combineforceswithyourapostles!.jpg",
    name: "Apeiron",
    genre: ["Strategy", "Adventure"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Foonie Magus",
    socials: {
      website: "https://apeiron.fooniemagus.com/",
      twitter: "https://x.com/apeironNFT",
      youtube: "https://www.youtube.com/watch?v=Hx6-H1g8KcM"
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "Apeiron is the world’s first NFT-based real-time strategic card-battler x god game. Apeiron features a unique card-based action-adventure combat system combined with god game simulation gameplay inspired by classic god games like Populous and Black & White. Players will be able to build up planets from above before taking control of a powerful Avatar to dive into PvE dungeons, fight in PvP arenas, and solve the mysteries of the mythologically-inspired godiverse. Start your own divine journey today!",
  },
  {
    id: "Axie-Champions",
    image: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1709005176-appicon_192.png",
    banner: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1708673410-mavis.png",
    name: "Axie Champions",
    genre: ["RPG","Puzzle","Match-3"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Bali games",
    socials: {
      website: "https://hub.skymavis.com/games/axie-champions?from=%2Fgames&name=Browse+Games&filter=partnershipType%253Dpartner-studio",
      twitter: "https://x.com/axiechampions?lang=es",
      youtube: "https://www.youtube.com/watch?v=S6FXGEraKqc"
    },
    platforms: ["Android"],
    description:
      "Axie Champions is a Match3 Puzzle RPG game, simple and easy-to-play for everyone. Gamers can collect, upgrade, and trade their Champions to win the Champions League!Login with your Mavis Account and let your Axies ride on the Champions!Various PVE modes, item Upgrades, and Champion Fusion will make your Champions Stronger.. Build your own Champion team for the Battle and aim for the Championship Prize!",
  },
  {
    id: "PuffGo",
    image: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1713172466-puffgologo-192_192.png",
    banner: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1713172499-1.jpg",
    name: "PuffGo",
    genre: ["Battle Royal"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Puffverse",
    socials: {
      website: "https://puffverse.pro/",
      twitter: "https://x.com/Puffverse",
      youtube: "https://youtu.be/J19Ypn7PV6w"
    },
    platforms: ["Android", "iOS"],
    description:
      "PuffGo is an on-chain multiplayer royale party game that allows players to earn while having fun. The game contains several levels and gameplay modes that offer players a choice of matchups from solo to multiplayer. Players can collect game characters with different appearances, personalities, abilities, and costumes. Players can also use different characters to participate in various levels of games and modes based on the advantages of each.",
  },
  {
    id: "Duet-Monsters",
    image: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1714645456-icon_512x512.png",
    banner: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1714645538-screenshots_1280x720_fix_01.png",
    name: "Duet Monsters",
    genre: ["Hypercasual","Music"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Cadenverse",
    socials: {
      website: "https://hub.skymavis.com/games/duet-monsters?from=%2Fgames&name=Browse+Games&filter=partnershipType%253Dpartner-studio",
      twitter: "https://x.com/duet_monsters?lang=es",
      youtube: "https://youtu.be/z342rbD2PhI"
    },
    platforms: ["Android", "iOS"],
    description:
      "Duet Monsters is a mobile dual-rhythm music game collaboration between Sky Mavis and Cadenverse where players control two monsters to collect falling fruit in sync with the music. Immerse yourself into the magical forest by building up a home for your Axies. It’s your way to play, choose solo to enjoy catchy tunes or battle against others to rise to the top of the global leaderboard. Set out on an adventurous journey through the magical world to restore harmony in the forest once and for all.",
  },
  {
    id: "Tribesters-Keeper-of-Secrets",
    image: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1715072899-kosgameicon192x192.png",
    banner: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1715073225-artgallery_1.jpg",
    name: "Tribesters - Keeper of Secrets",
    genre: ["Adventure"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Tribes Studio",
    socials: {
      website: "https://hub.skymavis.com/games/tribesters-ko-s?from=%2Fgames&name=Browse+Games&filter=partnershipType%253Dpartner-studio",
      twitter: "https://x.com/tribestersworld?lang=es",
      youtube: "https://youtu.be/AcCNoH7Hha4"
    },
    platforms: ["Windows","macOS"],
    description:
      "The Island of Solas is in a state of imbalance, with strange portals and creatures appearing all over the island The Island s magic has brought a being, our Wisp, to life to help the Tribesters solve the mystery and bring the Island back into balance. Each episode will introduce a new Village and Tribe, where players will earn NFT rewards and KUDOS points. Do you have what it takes to save the Island of Solas",
  },
  {
    id: "Puzzle-Champions",
    image: "https://cdn.skymavis.com/mavis-hub/assets/1733220489-mavisstorelogo.png",
    banner: "https://cdn.skymavis.com/mavis-hub/assets/1733219348-artgallery_01.png",
    name: "Puzzle Champions",
    genre: ["RPG","Puzzle","Match-3"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Bali games",
    socials: {
      website: "https://hub.skymavis.com/games/puzzle-champions?from=%2Fgames&name=Browse+Games&filter=partnershipType%253Dpartner-studio",
      twitter: "https://x.com/axiechampions?lang=es",
      youtube: "https://youtu.be/BmSOiTeeELY"
    },
    platforms: ["Windows","macOS"],
    description:
      "Puzzle Champions is a Match3 puzzle game with Champions. It is a simple and easy-to-play game that users can easily play while integrating RPG elements that allow gamers to collect, enhance, and trade their game items. Users can play Puzzle Champions by collecting Champions and leveling them up for PVP and PVE plays. There will be rich game content including gacha, collect, upgrade, fusion, artifact, and many other RPG elements while enjoying play to earn system.",
  },
  {
    id: "Axie-Quest",
    image: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1696404166-FA_axiequest_wildcard-KevinYap.png",
    banner: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1696481550-Battle-KevinYap.png",
    name: "Axie Quest",
    genre: ["RPG","Puzzle","Hypercasual"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Moonreach Games",
    socials: {
      website: "https://hub.skymavis.com/games/axie-quest?from=%2Fgames&name=Browse+Games&filter=genre%253Dpuzzle",
      twitter: "https://x.com/AxieQuest",
      youtube: "https://youtu.be/mnmZ5g_oWn8"
    },
    platforms: ["Windows","macOS","Android"],
    description:
      "Axie Quest: Puzzle Hunt is a game based on match-3 puzzle genre with a twist of exciting RPG elements. The game is designed based on the well known Axie Infinity NFTs.Players will be able to bring their Axies from Axie Infinity into an exciting quest in Axie Quest world. Explore and challenge the Wild Hunts using each Axie unique abilities, they are set to repel the wild monsters from bringing danger to the Axie Quest world. While the journey may be filled with challenges and brute forces, precious loots and magical artifacts can be found in the depths of the wild providing generous rewards at the same time strengthening the force of the Axies.In the Axie Quest world, in order to take-on the wild monsters, Axies help each other to train in the Dojo, enhancing their battle skills and preparing for the next big challenge in the Wild Hunt. The royalty of the Axie Quest world, rewards Axie adventurers who are able to show great courage and exceptional skills in The Arena. The strongest and mightiest Axies will have their name in the hall of fame shown on the leaderboard, the whole world cheers for them!",
  },
  {
    id: "Fight-League:Survivor",
    image: "https://cdn.skymavis.com/mavis-hub/assets/1733295903-fightleagueinfluencerlogo.png",
    banner: "https://cdn.skymavis.com/mavis-hub/assets/1733296304-fightleaguecomingtoronin.png",
    name: "Fight League: Survivor",
    genre: ["Survival"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "GMonsters",
    socials: {
      website: "https://playfightleague.com",
      twitter: "https://www.twitter.com/playfightleague",
      youtube: "https://youtu.be/m7melALgcsI"
    },
    platforms: ["Android"],
    description:
      "Fight League Survivor is a survival game - survival games are where players must keep their avatar alive in a hostile environment. Defend your avatar against hordes of monsters for 15 minutes per round - if you can! In Fight League Survivor, you begin each round as a controllable avatar in a large, closed arena. Your goal is to survive until the end of the round. At the beginning of each round, a few enemies will try to damage your avatar’s HP. Your avatar will auto-attack them using skills which you can upgrade during the round. Towards the end of the round, you’ll be fending off a massive mob of monsters and face off against at least one boss! Collect gems to fill your progress bar and level up your skills throughout the round. These will give you the offensive and defensive capabilities to emerge victorious.",
  },
  {
    id: "Forgotten-Runiverse",
    image: "https://cdn.skymavis.com/mavis-hub/assets/1733297993-forgottenruniverse_logo_256x256.png",
    banner: "https://cdn.skymavis.com/mavis-hub/assets/1733298094-battle2.jpg",
    name: "Forgotten Runiverse",
    genre: ["Turn-based","RPG","MMORPG"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Bisonic",
    socials: {
      website: "https://runiverse.world/",
      twitter: "https://x.com/runiversegame",
      youtube: "https://youtu.be/z1ALPAewJVU"
    },
    platforms: ["Windows","macOS"],
    description:
      "Adventure is calling! The Forgotten Runiverse is a free-to-play MMORPG that brings the world of the Forgotten Runes Wizard's Cult to life. Leveraging the Ronin blockchain, The Forgotten Runiverse revolves around a player-driven economy. As players explore the vast landscapes and battle formidable foes, they gather resources to craft armor, housing decor, and weapons. The Runiverse is open to anyone – begin your adventure, play, create, own land, and earn your place in the pantheon of legends.",
  },
  {
    id: "Fableborne",
    image: "https://cdn.skymavis.com/mavis-hub/assets/1733580300-image2022.png",
    banner: "https://cdn.skymavis.com/mavis-hub/assets/1733575345-fbg2.png",
    name: "Fableborne",
    genre: ["Strategy","Action RPG"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Fableborne",
    socials: {
      website: "https://twitter.com/fableborne",
      twitter: "https://fableborne.com/",
      youtube: "https://youtu.be/H-3AT7YLtkQ"
    },
    platforms: ["Android","iOS"],
    description:
      "Players embark on action-packed raids against other players’ kingdoms, battling player-crafted defenses in real-time using a variety of heroes, each with their own special abilities and playstyles. As you progress, you’ll strengthen your kingdom, collect resources, and upgrade your heroes to prepare for increasingly challenging raids. With a mix of PvP raids, PvE challenges, and competitive events, Fableborne offers a dynamic and engaging experience where strategy, skill, and creativity are key to conquering the Shatterlands and securing your place at the top! Join the Ronin Community! Connect with the largest Web3 gaming community and keep up with the latest Ronin news in Discord.",
  },
  {
    id: "Kaidro:Clan-Battles",
    image: "https://cdn.skymavis.com/mavis-hub/assets/1733307225-kaidrologo.jpeg",
    banner: "https://cdn.skymavis.com/mavis-hub/assets/1733296516-image2006.png",
    name: "Kaidro: Clan Battles",
    genre: ["Action RPG"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Kaidro",
    socials: {
      website: "https://kaidro.com/",
      twitter: "https://x.com/kaidrochronicle",
      youtube: "https://youtu.be/Y9i0Sh8XZrU"
    },
    platforms: ["Windows"],
    description:
      "Kaidro: Clan Battles is near-isometric multiplayer ARPG, that expands on top of the hit comic series Kaidro: The Awakening. Choose a clan, engage in competitive multiplayer battles, and beware of rivals and sinister forces from the Void. Alpha release imminent! Kaidro: Clan Battles offers players the opportunity to engage with multiple core gameplay elements. The game offers free-to-play competitive PvPvE matches played within various game modes, such as the “Bounty Hunt mode. Additionally, players can delve into customization and progression through interwoven systems like the Mech Garage and Astral Realm. Compelling story-driven content is purchasable through the Clan Paths and Faction Pass systems, and the innovative seasonal Clan Battle system introduces a “Meta” game where victory in the Bounty Hunt carries greater implications and rewards.",
  },
  {
    id: "The-Machines-Arena",
    image: "https://storage.googleapis.com/sm-prod-mavis-hub-cdn/assets/1688635545-1686639568-TMA-Thumbnail.png",
    banner: "https://cdn.skymavis.com/mavis-hub/assets/1733298714-tma_open-beta_009.jpg",
    name: "The Machines Arena",
    genre: ["Action RPG","Moba"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Directive Games",
    socials: {
      website: "https://www.themachinesarena.com/",
      twitter: "https://www.facebook.com/themachinesgame",
      youtube: "https://youtu.be/JFahsRbzvsE"
    },
    platforms: ["Windows"],
    description:
      "TMA is a free-to-play, top-down hero shooter with intense PvP and PvE combat. Earn rewards and digital collectibles in adrenaline-fueled battles.",
  },
  {
    id: "Cambria",
    image: "https://cdn.skymavis.com/mavis-hub/assets/1733371998-icon_logo_cambria.png",
    banner: "https://cdn.skymavis.com/mavis-hub/assets/1733372100-00.png",
    name: "Cambrian",
    genre: ["Strategy","Adventure","RPG","MMORPG","Survival"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Cambria",
    socials: {
      website: "https://cambria.gg",
      twitter: "https://x.com/playcambria",
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "Cambria: Risk-to-earn browser-based MMO with massive onchain stakes",
  },
  {
    id: "Cyberkongz-Play-and-Kollect",
    image: "https://cdn.skymavis.com/mavis-hub/assets/1733299504-cklogodisplay.jpg",
    banner: "https://cdn.skymavis.com/mavis-hub/assets/1733299652-junge-adventure-map.png",
    name: "Cyberkongz Play and Kollect",
    genre: ["Strategy","Adventure"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Cyberkongz",
    socials: {
      website: "https://www.cyberkongz.com/",
      twitter: "https://x.com/cyberkongz",
      youtube: "https://youtu.be/y_Y33pnBWgU"
    },
    platforms: ["Windows","macOS"],
    description:
      "Founded by the artist Myoo in March 2021, CyberKongz started as a unique and randomly generate collection of 1000, 34x34 pixelated NFT gorillas now known as the Genesis Collection. CyberKongz were the first to introduce and popularize a number of innovative NFT mechanics, such as unique tokenomics for their utility token $BANANA, which led to breeding and Babies. The VX collection, 3D avatars designed for the metaverse and gaming are the most interoperable avatar of any Web3 project. Supported by a passionate core community at our backbone, CyberKongz continues to push the boundaries in NFTs. The ecosystem, which now includes Play & Kollect, is one of the most expansive ecosystems in Web3. CyberKongz is focused on utility, innovation, and interoperability, while also expanding our IP into traditional Web2.",
  },
  {
    id: "Lumiterra",
    image: "https://cdn.skymavis.com/mavis-hub/assets/1733287396-logo256x2561.png",
    banner: "https://cdn.skymavis.com/mavis-hub/assets/1733287592-frame251.png",
    name: "Lumiterra",
    genre: ["Adventure","RPG", "MMORPG", "Action RPG","Survival"],
    isPlayable: true,
    isVerified: true,
    playableTime: "",
    creator: "Lumiterra",
    socials: {
      website: "https://lumiterra.net/",
      twitter: "https://x.com/LumiterraGame",
      youtube: "https://youtu.be/DM4lQXccTxM"
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "Lumiterra - A multiplayer, open-world survival crafting game where you can battle, farm with your friends or mysterious collected creatures in a vast world!",
  },
  {
    id: "Last-Odyssey|Commander-Assemble",
    image: "https://pbs.twimg.com/profile_images/1817801279139442688/xFq3NCQu_400x400.jpg",
    banner: "https://pbs.twimg.com/profile_banners/1722099335729643520/1712565647/1500x500",
    name: "Last Odyssey | Commander Assemble",
    genre: ["MMORTS"],
    isPlayable: false,
    isVerified: false,
    playableTime: "",
    creator: "Last Odyssey",
    socials: {
      website: "https://lastodyssey.io/",
      twitter: "https://x.com/LastOdyssey_io",
    },
    platforms: [],
    description:
      "Conquer to Earn ",
  },
  {
    id: "Sabong-Saga",
    image: "https://pbs.twimg.com/profile_images/1877223782852837376/WNkKMa5z_400x400.jpg",
    banner: "https://pbs.twimg.com/profile_banners/1849004909108289536/1731509783/1500x500",
    name: "Sabong Saga",
    genre: ["Auto-battler"],
    isPlayable: false,
    isVerified: false,
    playableTime: "",
    creator: "Sabong Saga",
    socials: {
      website: "https://www.sabongsaga.com/",
      twitter: "https://x.com/SabongSaga",
      youtube: "https://youtu.be/xxf0TUIc_3Y"
    },
    platforms: [],
    description:
      "",
  },
  {
    id: "Tatsumeeko",
    image: "https://pbs.twimg.com/profile_images/1876189369566220288/IWTo_LQd_400x400.jpg",
    banner: "https://pbs.twimg.com/profile_banners/781119824504250368/1736153380/1500x500",
    name: "Tatsumeeko",
    genre: ["RPG"],
    isPlayable: false,
    isVerified: false,
    playableTime: "",
    creator: "Tatsu Works Pte Ltd",
    socials: {
      website: "https://tatsumeeko.com/",
      twitter: "https://x.com/tatsumeeko",
    },
    platforms: [],
    description:
      "New Fantasy Lifesim RPG Game",
  },
  {
    id: "Kuroro-Wilds",
    image: "https://pbs.twimg.com/profile_images/1738321130828509184/mcwhV0_b_400x400.jpg",
    banner: "https://pbs.twimg.com/profile_banners/1691858355168464904/1708984489/1500x500",
    name: "Kuroro Wilds",
    genre: ["RPG"],
    isPlayable: false,
    isVerified: false,
    playableTime: "",
    creator: "kurorobeast",
    socials: {
      website: "https://www.kuroro.com/",
      twitter: "https://x.com/KuroroWilds",
    },
    platforms: ["Windows","macOS"],
    description:
      "A retro-inspired action-combat-based monster collecting RPG",
  },
  {
    id: "ChronosWorlds",
    image: "https://pbs.twimg.com/profile_images/1793975110749057024/9V12-eKo_400x400.jpg",
    banner: "https://pbs.twimg.com/profile_banners/1498776350701797378/1724167807/1500x500",
    name: "ChronosWorlds",
    genre: ["RPG"],
    isPlayable: false,
    isVerified: false,
    playableTime: "",
    creator: "Sphere_Studios",
    socials: {
      website: "https://chronosworlds.com/",
      twitter: "https://x.com/chronosworlds?lang=es",
      youtube: "https://youtu.be/9wd5gCDm_Xw"
    },
    platforms: ["Windows", "iOS", "Android"],
    description:
      "Fight fierce enemies and build your empire as you explore the dawn of time in a post-apocalyptic RPG. ",
  },
  {
    id: "Photo-Finish",
    image: "https://pbs.twimg.com/profile_images/1691232363181658112/j7E9viuX_400x400.png",
    banner: "https://pbs.twimg.com/profile_banners/3127687323/1692056192/1500x500",
    name: "Photo Finish",
    genre: ["Real Player"],
    isPlayable: true,
    isVerified: false,
    playableTime: "",
    creator: "Third Time Entertainment, Inc.",
    socials: {
      website: "https://photofinish.live/",
      twitter: "https://x.com/photofinishgame/",
    },
    platforms: ["Windows", "iOS", "Android", "macOS"],
    description:
      "Own virtual horses and run authentic races against REAL players for REAL money! ",
  },
];
